functionsDirectory = "C:\\Users\\ron\\Desktop\\example\\luxurfit-clothing\\netlify\\functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []

[build]
publish = "C:\\Users\\ron\\Desktop\\example\\luxurfit-clothing\\build"
publishOrigin = "ui"
commandOrigin = "ui"
command = "CI=false react-app-rewired build"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "22.11.0"
[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]